server:
  port: 8081
spring:
  application:
    name: fluxy-mock
  task:
    execution:
      pool:
        core-size: 5
        max-size: 20
        queue-capacity: 100
      thread-name-prefix: fluxy-async-
  datasource:
    url: jdbc:postgresql://localhost:5434/fluxy_mock
    username: fluxy
    password: fluxy
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
app:
  aws:
    region: us-east-1
    access-key: LSIAQAAAAAAVNCBMPNSG
    secret-key: LSIAQAAAAAAVNCBMPNSG
    sqs:
      endpoint: http://localhost:4566
      queue-name: fluxy-mock-queue